language: scala
scala:
  - 2.13.1
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
before_cache:
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt            -name "*.lock"               -print -delete
  - find $HOME/.coursier/cache -name "*.lock"               -print -delete
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom
